spring:
  application:
    name: SlideBot

  datasource:
    url: jdbc:postgresql://localhost:5432/Slide_Bot
    username: slide_bot
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

telegram:
  bot:
    token: 8122095609:AAGxVLSwHVlD5HO5B07_p7kff3gI1Cm5uto
    username: AI_Slide_Assistant_Bot

google:
  search:
    api-key: AIzaSyBRzFF9z7kg34gRUqJXQesbZSW3kw5Jodc   # Cloud Console → Google Search uchun
    cx: 724a919f9479e491e


gemini:
  api-key: AIzaSyDBPFqJLxV7En1p8dTVGbCRSBtuUuTVZvM    # AI Studio → Gemini uchun

logging:
  level:
    org.springframework: info
    uz.ai.slideshowbot: debug