spring:
  application:
    name: SlideBot

  datasource:
    url: jdbc:postgresql://localhost:5432/Slide_Bot
    username: slide_bot
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: AI_Slide_Assistant_Bot

google:
  search:
    api-key: ${GOOGLE_SEARCH_API_KEY}
    cx: ${GOOGLE_SEARCH_CX}

gemini:
  api-key: ${GEMINI_API_KEY}

logging:
  level:
    org.springframework: info
    uz.ai.slideshowbot: debug