spring:
  application:
    name: SlideBot

  datasource:
    url: jdbc:postgresql://localhost:5432/Slide_Bot
    username: slide_bot
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

telegram:
  bot:
    token: 8122095609:AAGxVLSwHVlD5HO5B07_p7kff3gI1Cm5uto
    username: AI_Slide_Assistant_Bot

google:
  search:
    api-key: "AIzaSyCZNPZkCsyH3jF4Aybsbs3MG_HDlhO7wl0"
    cx: "724a919f9479e491e"


gemini:
  api-key: "AIzaSyBc2hwdtnLHAGdiqZaM70Z4yOUqqzy5bPQ"

logging:
  level:
    org.springframework: info
    uz.ai.slideshowbot: debug